[project]
name = "sqlalchemy-p34"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=4.3.0",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.43",
]
